services:
  postgres-dev:
    image: postgres:18.0-alpine3.22
    container_name: keruberosu-postgres-dev
    environment:
      POSTGRES_USER: keruberosu
      POSTGRES_PASSWORD: keruberosu_dev_password
      POSTGRES_DB: keruberosu_dev
    ports:
      - "15432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keruberosu"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:18.0-alpine3.22
    container_name: keruberosu-postgres-test
    environment:
      POSTGRES_USER: keruberosu
      POSTGRES_PASSWORD: keruberosu_test_password
      POSTGRES_DB: keruberosu_test
    ports:
      - "25432:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keruberosu"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-dev-data:
  postgres-test-data:
